---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-app
  namespace: prod-env
spec:
  selector:
    matchLabels:
      app: group-app
  template:
    metadata:
      labels:
        app: group-app
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: mimijoso/josozikora:1.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
