apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-app
  namespace: prod-env
  
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: group-app   
  template:
    metadata:
      labels:
        app: group-app
    spec:
      containers:
      - name: group-app
        image: mimijoso/josozikora:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
